name: WarmUp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: Say Hello
            run: echo "Hello World"

          - name: Simple Math
            run: |
              a=1
              b=2
              sum=$((a+b))
              echo "Sum is: $sum"

          - name: Control Flow
            run: |
              a=18
              if: a >= 18
              echo: "Adult"
            



      
