name: VerificationTestBuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello World"
      
      - name: Simple Math
        run: |
          a=1
          b=2
          sum=$((a+b))
          echo "Sum is: $sum"